subreddits_1 = {
    "Discussion and Stories": [
        "AskReddit ",
        "IAmA ",
        "bestof ",
        "fatpeoplestories ",
        "pettyrevenge ",
        "TalesFromRetail ",
        "DoesAnybodyElse ",
        "CrazyIdeas ",
    ],
    "Emotional Reaction Fuel": [
        "WTF ",
        "aww ",
        "cringepics ",
        "cringe ",
        "JusticePorn ",
        "MorbidReality ",
        "rage ",
        "mildlyinfuriating ",
        "creepy ",
        "creepyPMs ",
        "nosleep ",
        "nostalgia ",
    ],
    "Entertainment - Gaming": [
        "gaming ",
        "leagueoflegends ",
        "pokemon ",
        "Minecraft ",
        "starcraft ",
        "Games ",
        "DotA2 ",
        "skyrim ",
        "tf2 ",
        "magicTCG ",
        "wow ",
        "KerbalSpaceProgram ",
        "mindcrack ",
        "Fallout ",
        "roosterteeth ",
        "Planetside ",
        "gamegrumps ",
        "battlefield3 ",
        "zelda ",
        "darksouls ",
        "masseffect ",
    ],
    "Entertainment - Television": [
        "arresteddevelopment ",
        "gameofthrones ",
        "doctorwho ",
        "mylittlepony ",
        "community ",
        "breakingbad ",
        "adventuretime ",
        "startrek ",
        "TheSimpsons ",
        "futurama ",
        "HIMYM ",
        "DunderMifflin ",
        "thewalkingdead ",
    ],
    "Entertainment - Other (Movies/Music/Franchies/Misc)": [
        "Music ",
        "movies ",
        "harrypotter ",
        "StarWars ",
        "DaftPunk ",
        "hiphopheads ",
        "anime ",
        "comicbooks ",
        "geek ",
        "batman ",
        "TheLastAirbender ",
        "Naruto ",
        "FanTheories ",
    ],
    "Humor": [
        "funny ",
        "AdviceAnimals ",
        "fffffffuuuuuuuuuuuu ",
        "4chan ",
        "ImGoingToHellForThis ",
        "firstworldanarchists ",
        "circlejerk ",
        "MURICA ",
        "facepalm ",
        "Jokes ",
        "wheredidthesodago ",
        "polandball ",
        "TrollXChromosomes ",
        "comics ",
        "nottheonion ",
        "britishproblems ",
        "TumblrInAction ",
        "onetruegod ",
    ],
    "Images, Gifs, and Videos": [
        "pics ",
        "videos ",
        "gifs ",
        "reactiongifs ",
        "mildlyinteresting ",
        "woahdude ",
        "FiftyFifty ",
        "FoodPorn ",
        "HistoryPorn ",
        "wallpapers ",
        "youtubehaiku ",
        "Unexpected ",
        "photoshopbattles ",
        "AnimalsBeingJerks ",
        "cosplay ",
        "EarthPorn ",
        "QuotesPorn ",
        "awwnime ",
        "AbandonedPorn ",
        "carporn ",
        "PerfectTiming ",
        "OldSchoolCool ",
        "RoomPorn ",
        "Pareidolia ",
        "MapPorn ",
        "tumblr ",
        "techsupportgore ",
        "PrettyGirls ",
        "itookapicture ",
    ],
    "Learning and Thinking": [
        "todayilearned ",
        "science ",
        "askscience ",
        "space ",
        "AskHistorians ",
        "YouShouldKnow ",
        "explainlikeimfive ",
    ],
    "Lifestyle and Help": [
        "trees ",
        "MakeupAddiction ",
        "cats ",
        "LifeProTips ",
        "RedditLaqueristas ",
        "Random_Acts_Of_Amazon ",
        "food ",
        "guns ",
        "tattoos ",
        "corgi ",
        "teenagers ",
        "GetMotivated ",
        "motorcycles ",
        "sex ",
        "progresspics ",
        "DIY ",
        "bicycling ",
        "Fitness ",
        "lifehacks ",
        "longboarding ",
        "Frugal ",
        "drunk ",
        "Art ",
        "loseit ",
        "Military ",
    ],
    "News and Issues": [
        "politics ",
        "worldnews ",
        "news ",
        "conspiracy ",
        "Libertarian ",
        "TrueReddit ",
        "Conservative ",
        "offbeat ",
    ],
    "Places": ["canada ", "toronto ", "australia ", "unitedkingdom "],
    "Race, Gender, and Identity": [
        "atheism ",
        "TwoXChromosomes ",
        "MensRights ",
        "gaybros ",
        "lgbt ",
    ],
    "Sports": [
        "nba ",
        "soccer ",
        "hockey ",
        "nfl ",
        "formula1 ",
        "baseball ",
        "MMA ",
        "SquaredCircle ",
    ],
    "Technology": ["technology ", "Android ", "Bitcoin ", "programming ", "apple "],
}

subreddits_2 = {
    "General Subjects and News###": [
        "worldnews",
        "news",
        "worldpolitics",
        "Worldevents",
        "business",
        "Economics",
        "environment",
        "energy",
        "law",
        "education",
        "government",
        "history",
        "PoliticsPDFs",
        "WikiLeaks",
        "SOPA",
        "NewsPorn",
        "worldnews2",
        "AnarchistNews",
        "republicofpolitics",
        "LGBTnews",
        "politics2",
        "economics2",
        "environment2",
    ],
    "Regional###": [
        "politics",
        "uspolitics",
        "AmericanPolitics",
        "canada",
        "AmericanGovernment",
        "ukpolitics",
        "euro",
        "Palestine",
        "eupolitics",
        "MiddleEastNews",
        "Israel",
        "india",
        "pakistan",
        "Cascadia",
        "iran",
        "wisconsinpolitics",
    ],
    "Ideological Based": [
        "Libertarian",
        "Anarchism",
        "socialism",
        "progressive",
        "Conservative",
        "americanpirateparty",
        "democrats",
        "Liberal",
        "new_right",
        "Republican",
        "egalitarian",
        "demsocialist",
        "LibertarianLeft",
        "Liberty",
        "Anarcho_Capitalism",
        "alltheleft",
        "neoprogs",
        "tea_party",
        "voluntarism",
        "labor",
        "blackflag",
        "GreenParty",
        "democracy",
        "IWW",
        "PirateParty",
        "Marxism",
        "piratenpartei",
        "Objectivism",
        "LibertarianSocialism",
        "peoplesparty",
        "Capitalism",
        "Anarchist",
        "feminisms",
        "republicans",
        "Egalitarianism",
        "anarchafeminism",
        "Communist",
        "socialdemocracy",
        "Postleftanarchism",
        "RadicalFeminism",
        "AnarchoPacifism",
        "conservatives",
        "republicanism",
    ],
    "Discussion and Examination of Political Ideas and Concepts###": [
        "Freethought",
        "Foodforthought",
        "StateOfTheUnion",
        "moderatepolitics",
        "PoliticalDiscussion",
        "equality",
        "culturalstudies",
        "politicalhumor",
        "propagandaposters",
        "SocialScience",
        "PoliticalPhilosophy",
        "media",
        "culture",
        "racism",
        "corruption",
        "ipr",
        "chomsky",
        "propaganda",
        "PeterSchiff",
        "votingtheory",
        "ReligionInAmerica",
        "EconPapers",
        "debate",
        "FoodSovereignty",
        "environmental_policy",
    ],
    "Activism and Reform###": [
        "lgbt",
        "MensRights",
        "collapse",
        "OperationGrabAss",
        "HackBloc",
        "rpac",
        "Bad_Cop_No_Donut",
        "Anticonsumption",
        "Permaculture",
        "food2",
        "anonymous",
        "censorship",
        "feminism",
        "Sunlight",
        "privacy",
        "occupywallstreet",
        "resilientcommunities",
        "ChangeNow",
        "rpa",
        "GenderEgalitarian",
        "activism",
        "revolution",
        "NaziHunting",
        "prisonreform",
        "tsa",
        "electionreform",
        "troubledteens",
        "firstamendment",
        "sensiblewashington",
        "Thewarondrugs",
        "union",
        "Good_Cop_Free_Donut",
        "strikeaction",
        "YouthRights",
        "PhxClassWarCouncil",
        "humanrights",
        "CPAR",
        "whiterights",
    ],
    "Politicians and Political Campaigns": [
        "obama",
        "ronpaul",
        "Kucinich",
        "PalinProblem",
        "GaryJohnson",
        "Bachmann2012",
        "USPE12",
        "2012Elections",
        "Campaigns",
        "perry2012",
        "huntsman",
        "huntsman2012",
        "newt2012",
        "romney",
    ],
    "War and Peace###": [
        "BlackOps",
        "Intelligence",
        "MideastPeace",
        "EndlessWar",
        "antiwar",
        "war",
        "peace",
        "afghanistan",
        "Libya",
    ],
    "Conspiracy": [
        "conspiracy",
        "911truth",
        "climateskeptics",
        "infograffiti",
        "conspiracyhub",
        "redditorsfor911truth",
    ],
}

members = [
    "mayank",
    "amul",
    "shivansh",
    "tanishq",
    "pulak",
    "dhruv",
    "murali",
    "ritvik",
    "siddharth",
    "tejasvi",
]
